### ISSUE TITLE
python software  

### ISSUE THREAD

**Issue by electrosoft2022** [rtek1000/Curve-Tracer-ATmega328#1]
Hi good jobs for ope hardware curve tracer but cant find a python software to test it 
thanks BR

**Comment by rtek1000** [comment]
Hello, there is no Python code available.

See this one: https://github.com/rtek1000/Curve-Tracer-ESP32

There is an HTML code that can serve as a basis for writing Python code.

https://github.com/rtek1000/Curve-Tracer-ESP32/blob/main/ESP32CT_Software/data/index.html

Let me close this issue for now, if necessary, feel free to reopen it, thank you.
